### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by zachlatta** [jjasghar/docker-meetbot#1]
From building a vanilla clone of this repo, I got the following logs (with the error at the end):

https://gist.github.com/zachlatta/9dc1afcbee98a9d03b41

**Comment by jjasghar** [comment]
Damn, ok, I'll see if i can find another mirror.

**Comment by jjasghar** [comment]
This should be resolved with https://github.com/jjasghar/docker-meetbot/commit/91acce8e5d61e60fe06f3c9da4959ec4bee11cd6 please reopen if you are still having issues.
